
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'E97277AFFA6EBE670AFD5CB8E04B45B3'
    
_lr_action_items = {'RPAREN':([1,3,4,5,9,12,13,14,15,16,],[-3,-6,-7,-8,14,-5,-4,-9,-1,-2,]),'DIVIDE':([1,3,4,5,12,13,14,15,16,],[7,-6,-7,-8,-5,-4,-9,7,7,]),'TIMES':([1,3,4,5,12,13,14,15,16,],[8,-6,-7,-8,-5,-4,-9,8,8,]),'ICONST':([0,2,7,8,10,11,],[4,4,4,4,4,4,]),'LPAREN':([0,2,7,8,10,11,],[2,2,2,2,2,2,]),'PLUS':([1,3,4,5,6,9,12,13,14,15,16,],[-3,-6,-7,-8,10,10,-5,-4,-9,-1,-2,]),'MINUS':([1,3,4,5,6,9,12,13,14,15,16,],[-3,-6,-7,-8,11,11,-5,-4,-9,-1,-2,]),'ID':([0,2,7,8,10,11,],[5,5,5,5,5,5,]),'$end':([1,3,4,5,6,12,13,14,15,16,],[-3,-6,-7,-8,0,-5,-4,-9,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,2,10,11,],[1,1,15,16,]),'expression':([0,2,],[6,9,]),'factor':([0,2,7,8,10,11,],[3,3,12,13,3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parser.py',21),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','parser.py',25),
  ('expression -> term','expression',1,'p_expression_term','parser.py',29),
  ('term -> term TIMES factor','term',3,'p_term_times','parser.py',33),
  ('term -> term DIVIDE factor','term',3,'p_term_div','parser.py',37),
  ('term -> factor','term',1,'p_term_factor','parser.py',41),
  ('factor -> ICONST','factor',1,'p_factor_num','parser.py',45),
  ('factor -> ID','factor',1,'p_factor_id','parser.py',49),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parser.py',53),
]
